language: perl
before_install:
  - sudo add-apt-repository restricted -y
  - sudo add-apt-repository universe -y
  - sudo add-apt-repository multiverse -y
  # - sudo add-apt-repository ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - >
    sudo apt-get -qq install -y sharutils, libncurses5-dev,
    libreadline-dev, freeglut3-dev, libxi-dev, libxmu-dev,
    libgsl-dev, libnetpbm10-dev, ffmpeg, gfortran, libfftw3-dev,
    pkg-config
  - >
    sudo cpanm Devel::CheckLib, ExtUtils::MakeMaker, Test::Exception,
    Filter::Util::Call, Filter::Simple, Module::Compile, Inline,
    Module::Install, Inline::C, Data::Dumper, Storable,
    Devel::REPL, File::Map, ExtUtils::F77, Path::Class, PDL,
    PDL::FFTW3
  - sudo cpanm --force Module::Build::Pluggable::PDL
perl:
  - "5.28"
  - "5.14"
  - "5.10"
after_failure:
  - cat /home/travis/.cpanm/latest_build/build.log
